# Generated by Django 3.2 on 2022-11-21 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_users',
        ),
        migrations.AddField(
            model_name='comment',
            name='recomends',
            field=models.ManyToManyField(related_name='recomends', to=settings.AUTH_USER_MODEL),
        ),
    ]
