# Generated by Django 3.2 on 2022-11-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20221121_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
